---
- name: install lua packages
  action: package
  become: true
  become_user: root
  args:
    name: "{{ item }}"
    state: present
  with_items:
    - lua
    - lua-devel
    - luarocks
- name: install lua packages
  action: luarocks
  args:
    name: "{{ item }}"
    state: present
    local: yes
  with_items:
    - busted
    - luacov
