---
- name: download rpmfusion free repo
  action: get_url
  args:
    url: "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    dest: "{{ ansible_pkgs_dir }}/rpmfusion-free-release-{{ ansible_distribution_major_version }}-2.noarch.rpm"
- name: install rpmfusion free repo
  action: package
  become: true
  become_user: root
  args:
    name: "{{ ansible_pkgs_dir }}/rpmfusion-free-release-{{ ansible_distribution_major_version }}-2.noarch.rpm"
    state: present
- name: download rpmfusion non-free repo
  action: get_url
  args:
    url: "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    dest: "{{ ansible_pkgs_dir }}/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}-2.noarch.rpm"
- name: install rpmfusion non-free repo
  action: package
  become: true
  become_user: root
  args:
    name: "{{ ansible_pkgs_dir }}/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}-2.noarch.rpm"
    state: present
