---
- name: Check If maven is already installed or not
  shell: "mvn -version | grep -w 'Apache Maven' | awk '{print $3}'"
  register: maven_installed
- name: install maven packages
  action: package
  become: true
  become_user: root
  args:
    name: "{{ item }}"
    state: present
  with_items:
    - maven
