---
- name: install python packages
  action: package
  become: true
  become_user: root
  args:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - python3-pip
    - python-virtualenv
- name: install python2 packages
  action: pip
  args:
    executable: /usr/bin/pip
    extra_args: "--user"
    name: "{{ item }}"
    state: latest
  with_items:
    - legit
- name: install python3 packages
  action: pip
  args:
    executable: /usr/bin/pip3
    extra_args: "--user"
    name: "{{ item }}"
    state: latest
  with_items:
    - jedi
    - flake8
    - autopep8
    - isort
    - pytest
    - pytest-watch
    - pytest-flake8
    - pytest-isort
    - pytest-hidecaptured
- name: install python repo build tools
  action: package
  become: true
  become_user: root
  args:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-invoke
