---
- name: create bin dir
  action: file
  args:
    path: "{{ running_user_dir }}/bin"
    state: directory
- name: install scripts
  action: copy
  args:
    src: "{{ item }}"
    dest: "{{ running_user_dir }}/bin/{{ item }}"
    mode: 0755
  with_items:
    - e
    - npm-do
    - patch-create
    - search
    - vim-raw
