---
- name: install graphic tools
  action: package
  become: true
  become_user: root
  args:
    name: "{{ item }}"
    state: present
  with_items:
    - inkscape
    - gimp
- name: create inkscape config dir
  action: file
  args:
    path: "{{ running_user_dir }}/.config/inkscape"
    state: directory
- name: create inkscape palettes dir
  action: file
  args:
    path: "{{ running_user_dir }}/.config/inkscape/palettes"
    state: directory
- name: install inkscape material palette
  action: copy
  args:
    src: "Material_Design.gpl"
    dest: "{{ running_user_dir }}/.config/inkscape/palettes/Material_Design.gpl"
    mode: 0644
