---
- hosts: localhost
  connection: local

  roles:
    - pre
    - rpmfusion
    - git
    - cli_tools
    - bin
    - shell
    - zsh
    - nodejs
    - python
    - ruby
    - lua
    - maven
    - vscode
    - docker
    - vagrant
    - rpmmock
    - graphics

  vars_files:
    - ../vars/main.yml
  vars:
    editor_rpmdev_enable: yes
